import React, { useState } from "react";
import "./Form16Explainer.css";

const formSections = [
  {
    title: "🧾 Part A – TDS Summary",
    content:
      "Contains employer name, TAN, PAN, TDS deducted and deposited. Generated by TRACES. Must be digitally signed.",
  },
  {
    title: "💼 Employer & Employee Details",
    content:
      "Includes employer name, PAN, address and your own PAN, name, and employment duration.",
  },
  {
    title: "💰 Gross Salary",
    content:
      "Basic salary, HRA, bonuses, and all taxable allowances. Found in Part B under 'Details of Salary Paid'.",
  },
  {
    title: "🧾 Exemptions & Deductions",
    content:
      "Shows 80C (LIC, PPF), 80D (Health), 80E (Education loan) deductions declared and approved by employer.",
  },
  {
    title: "📉 Taxable Income",
    content:
      "Gross income - deductions = taxable income. Used to calculate income tax slab.",
  },
  {
    title: "💸 TDS Deducted",
    content:
      "Shows total tax deducted by employer and deposited monthly with the government.",
  },
  {
    title: "✅ Verification Section",
    content:
      "Signed by employer HR or authorized signatory with place and date of generation.",
  },
];

export default function Form16Explainer() {
  const [activeIndex, setActiveIndex] = useState(null);

  const toggleIndex = (index) => {
    setActiveIndex(index === activeIndex ? null : index);
  };

  return (
    <div className="form16-explainer">
      <h2>📄 Form-16 Visual Explainer</h2>
      <p className="intro">
        Click on each section below to understand your Form-16 in detail.
      </p>

      <div className="accordion">
        {formSections.map((section, index) => (
          <div key={index} className="accordion-item">
            <div
              className="accordion-title"
              onClick={() => toggleIndex(index)}
            >
              {section.title}
              <span>{activeIndex === index ? "−" : "+"}</span>
            </div>
            {activeIndex === index && (
              <div className="accordion-content">{section.content}</div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
